config/routes.rb
Rails.application.routes.draw do
  resources :proyects
  resources :social_media
  get 'users', to: 'categories#index'
  get 'users/sing_up', to: 'users#new'
  devise_for :users
  resources :categories, only: %i[index show new create]
  resources :articles, only: %i[index show new create edit update] do
    resources :votes, only: %i[create destroy]
  end

  root 'categories#index'
end

app/controllers/social_media_controller.rb
class SocialMediaController < ApplicationController
  before_action :set_social_medium, only: %i[ show edit update destroy ]

  # GET /social_media or /social_media.json
  def index
    @social_media = SocialMedium.all
  end

  # GET /social_media/1 or /social_media/1.json
  def show
  end

  # GET /social_media/new
  def new
    @social_medium = SocialMedium.new
  end

  # GET /social_media/1/edit
  def edit
  end

  # POST /social_media or /social_media.json
  def create
    @social_medium = SocialMedium.new(social_medium_params)

    respond_to do |format|
      if @social_medium.save
        format.html { redirect_to @social_medium, notice: "Social medium was successfully created." }
        format.json { render :show, status: :created, location: @social_medium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @social_medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_media/1 or /social_media/1.json
  def update
    respond_to do |format|
      if @social_medium.update(social_medium_params)
        format.html { redirect_to @social_medium, notice: "Social medium was successfully updated." }
        format.json { render :show, status: :ok, location: @social_medium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @social_medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_media/1 or /social_media/1.json
  def destroy
    @social_medium.destroy
    respond_to do |format|
      format.html { redirect_to social_media_url, notice: "Social medium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_medium
      @social_medium = SocialMedium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def social_medium_params
      params.require(:social_medium).permit(:name, :url)
    end
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/views/social_media/_form.html.erb
<%= simple_form_for(@social_medium) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/social_media/edit.html.erb
<h1>Editing Social Medium</h1>

<%= render 'form', social_medium: @social_medium %>

<%= link_to 'Show', @social_medium %> |
<%= link_to 'Back', social_media_path %>

app/views/social_media/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Social Media</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_media.each do |social_medium| %>
      <tr>
        <td><%= social_medium.name %></td>
        <td><%= social_medium.url %></td>
        <td><%= link_to 'Show', social_medium %></td>
        <td><%= link_to 'Edit', edit_social_medium_path(social_medium) %></td>
        <td><%= link_to 'Destroy', social_medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social Medium', new_social_medium_path %>

app/views/social_media/new.html.erb
<h1>New Social Medium</h1>

<%= render 'form', social_medium: @social_medium %>

<%= link_to 'Back', social_media_path %>

app/views/social_media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @social_medium.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @social_medium.url %>
</p>

<%= link_to 'Edit', edit_social_medium_path(@social_medium) %> |
<%= link_to 'Back', social_media_path %>