config/routes.rb
Rails.application.routes.draw do
  resources :proyects
  resources :social_media
  get 'users', to: 'categories#index'
  get 'users/sing_up', to: 'users#new'
  devise_for :users
  resources :categories, only: %i[index show new create]
  resources :articles, only: %i[index show new create edit update] do
    resources :votes, only: %i[create destroy]
  end

  root 'categories#index'
end

app/models/proyect.rb
class Proyect < ApplicationRecord
  belongs_to :framework
  belongs_to :language
  belongs_to :skill
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: %i[ show edit update destroy ]

  # GET /proyects or /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1 or /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects or /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: "Proyect was successfully created." }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1 or /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: "Proyect was successfully updated." }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1 or /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: "Proyect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyect_params
      params.require(:proyect).permit(:name, :framework_id, :language_id, :skill_id, :other, :imageurl, :live_url, :source_url)
    end
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/proyects/_form.html.erb
<%= simple_form_for(@proyect) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :framework %>
    <%= f.association :language %>
    <%= f.association :skill %>
    <%= f.input :other %>
    <%= f.input :imageurl %>
    <%= f.input :live_url %>
    <%= f.input :source_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<h1>Editing Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Show', @proyect %> |
<%= link_to 'Back', proyects_path %>

app/views/proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Framework</th>
      <th>Language</th>
      <th>Skill</th>
      <th>Other</th>
      <th>Imageurl</th>
      <th>Live url</th>
      <th>Source url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= proyect.name %></td>
        <td><%= proyect.framework_id %></td>
        <td><%= proyect.language_id %></td>
        <td><%= proyect.skill_id %></td>
        <td><%= proyect.other %></td>
        <td><%= proyect.imageurl %></td>
        <td><%= proyect.live_url %></td>
        <td><%= proyect.source_url %></td>
        <td><%= link_to 'Show', proyect %></td>
        <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
        <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyect', new_proyect_path %>

app/views/proyects/new.html.erb
<h1>New Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Back', proyects_path %>

app/views/proyects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proyect.name %>
</p>

<p>
  <strong>Framework:</strong>
  <%= @proyect.framework_id %>
</p>

<p>
  <strong>Language:</strong>
  <%= @proyect.language_id %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @proyect.skill_id %>
</p>

<p>
  <strong>Other:</strong>
  <%= @proyect.other %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @proyect.imageurl %>
</p>

<p>
  <strong>Live url:</strong>
  <%= @proyect.live_url %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @proyect.source_url %>
</p>

<%= link_to 'Edit', edit_proyect_path(@proyect) %> |
<%= link_to 'Back', proyects_path %>